title: "Chess Arena - Your Move"
description: "Chess Arena: Real-time chess strategy meets MOBA chaos. Think three moves ahead. React in real-time."
url: "https://razonin4k.github.io"
baseurl: "/chess-arena-minisite"
timezone: America/New_York
