title: Your Move · Mini-Project
description: Chess × MOBA concept: $1K plan, creatives, video, and safety stance.
url: "https://<your-username>.github.io"
baseurl: "/botez-mini-project"
timezone: America/New_York
